export enum ActionType {
  SEND_DATA = "SEND_DATA",
  GET_DEFAULT_DATA = "GET_DEFAULT_DATA",
  GET_DATA_LOADING = "GET_DATA_LOADING",
  GET_DATA_SUCCESS = "GET_DATA_SUCCESS",
  GET_DATA_FAIL = "GET_DATA_FAIL",
}
